# Generated by Django 6.0.2 on 2026-03-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_categories_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryy',
            new_name='category',
        ),
    ]
